### ISSUE TITLE
Running npm install shows several vulernabilities

### ISSUE THREAD

**Issue by dnnibm** [IBM/marked-it-cli#11]
```
» npm install
added 45 packages from 282 contributors and audited 66 packages in 0.927s
found 3 vulnerabilities (1 low, 1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

Suggested course of action from `npm audit`:
`npm install js-yaml@3.13.1` and `npm update mkdirp --depth 2`

This is important because any projects that use `marked-it-cli` show the js-yaml vulnerabilities. Thanks.

**Comment by grant-g** [comment]
Fixed in 0.21.1.
